# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirement_streamlit.txt .
RUN pip install --no-cache-dir -r requirement_streamlit.txt 

# # Copy the Streamlit app
# COPY streamlit_app.py .

# Expose the Streamlit port
EXPOSE 8501

# # Default command to run Streamlit
# CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
